# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Antoine Bourget's Website
email: antoine.brgt@gmail.com
description: Antoine Bourget's Website. Science and History seen from Oviedo
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://antoinebourget.org" # the base hostname & protocol for your site, e.g. http://example.com
image_path: "/attachments/images"
file_path: "/attachments/files"
#twitter_username: AntoineBrgt
#github_username:  jekyll
paginate: 10
paginate_path: "/blog/page:num/"
google_analytics: "UA-68657513-1"
disqus:
  shortname: "antoine_bourget"


# Build settings
markdown: kramdown
#markdown: maruku
theme: minima
gems:
  - jekyll-feed
  - jekyll-paginate
exclude:
  - Gemfile
  - Gemfile.lock
